
@noinline function test_primer_match()
    @testset "Primer Match" begin
        r1= fqreadrecord("@M03737:51:000000000-KTBYH:1:1101:21125:2738 1:N:0:GTATCGTCGT+CACCTGTT
ACCGATGAAGAACGCAGCGAAATGCGATACGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCGCCAGTATTCTGGCGGGCATGCCCGTTCGAGCGTCATTTCAACCCTCAAGCCCTGCTTGGTGTTGGGGACCGGCTCAGCGGGTGCGGGCTTCGGCCCGTCCCGTGCCGCCCCCGAAATGGATCGGCGGTCTCGTCGCAGCCTTCTTTGCGTAGTAACATACCACCTCGCAACAGGAGCGCGGCGCGGCCACTGCCGTAAAACGCCCAACTTTT
+
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCEGGGGGGGGGGGGGGGFGGGGGGDG:FGGGFEFFFFFFFFFGFGD<@E;AFBFFF=FFFG@FEFFFFFFF?BFFFFFFFBFF:D>B>?F?61186ADF9;BFFB09A<")
        
        r2 = fqreadrecord("@M03737:51:000000000-KTBYH:1:1101:21125:2738 2:N:0:GTATCGTCGT+CACCTGTT
CTTATTGATATGCTTAAGTTCAGCGGGTATTCCTACCTGATTCGAGGTCAACTCTAAAAAGTTGGGCGTTTTACGGCAGTGGCCGCGCCGCGCTCCTGTTGCGAGGTGGTATGTTACTACGCAAAGAAGGCTGCGACGAGACCGCCGATCCATTTCGGGGGCGGCACGGGACGGGCCGAAGCCCGCACCCGCTGAGCCGGTCCCCAACACCAAGCAGGGCTTGAGGGTTGAAATGACGCTCGAACGGGCATGCCCGCCAGAATACTGGCGGGCGCAAGGGGGGTTCAAAGGTTCGAAGAA
+
CCCCCGGGGGGGGGGGGGGGGGGGEDDFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG3BGFFGGGDGGFFFFEBFFFFF:BFF>?4:>12868?FBFBDB253-((41<:1122((.9:??696-4:)).)-4,43((342900600((,,62)-(,)43((4,(")

        primer1 = dna"AHCGATGAAGAACRYAG"
        primer2 = dna"CTTATTGATATGCTTAAGTTCAG"

        ps = PrimerSet(primer1, primer2)
    end
end