#!/usr/bin/env julia

@info "Atria without precompilation. It may take a while to precompile."

using Pkg

Pkg.activate(dirname(@__DIR__))
Pkg.instantiate()

include(joinpath(@__DIR__, "Atria.jl"))

Atria.julia_main()
